Repository croct-tech/plug-rule-engine-js, pull requests merged in 2020-05, with the labels that each got.

#2 Fix plugin typing augmentation
  src/index.ts
Labels: bug

#3 Remove CODEOWNERS e add PR template
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: maintenance

#4 Tweak readme and package.json
  README.md
  package.json
Labels: maintenance

#5 Fix build link in readme
  README.md
Labels: maintenance

#6 Add runtime validation for options
  src/index.ts
  src/plugin.ts
  test/index.test.ts
  test/mocks.ts
  test/plugin.test.ts
Labels: enhancement

#7 Allow enabling/disabling extension
  package-lock.json
  package.json
  src/extension.ts
  src/plugin.ts
  test/mocks.ts
  test/plugin.test.ts
Labels: feature

#8 Remove non-essential comment
  README.md
Labels: maintenance

#10 Improve options schema performance
  src/plugin.ts
Labels: enhancement

#11 Add tests for valid definitions
  test/index.test.ts
Labels: enhancement

#12 Bump Plug version to 0.2.0-beta.8
  package-lock.json
  package.json
Labels: maintenance

#13 Remove app ID from example in readme
  README.md
Labels: documentation

#14 Fix definition augmentation
  package-lock.json
  package.json
  src/plugin.ts
Labels: bug

#15 Fix Github token
  .github/workflows/release-drafter.yaml
Labels: maintenance

#16 Fix options typing
  src/index.ts
Labels: bug

#17 Export ES2015 modules to solve bundling issues with CommonJS
  tsconfig.json
Labels: enhancement

#18 Bump Plug version to 0.2.1
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  test/index.test.ts
Labels: maintenance

#19 Import Typescript runtime
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#21 Add option to wait for page to load
  src/index.ts
  src/plugin.ts
  test/index.test.ts
  test/plugin.test.ts
Labels: feature

#22 Fix flag option normalization
  src/plugin.ts
Labels: bug

#23 Bump plug to version 0.3.0
  package-lock.json
  package.json
Labels: maintenance
